refactor env to seperate env variables based on category
WesionaryTEAM/go_clean_architecture pull request #115
Opened 2024-11-08 05:53 UTC by projectmap

# Jira url

1. https://wesionary-team.atlassian.net/browse/BAC-110

# Description
- Refactored env to seperate env variables based on category

2024-11-08 06:03 UTC, paudelgaurav requested changes

2024-11-08 06:03 UTC, paudelgaurav commented on pkg/framework/env.go
> +	UserPoolID        string `mapstructure:"COGNITO_USER_POOL_ID"`
Let's include Cognito in this attributes
For eg: CognitoClientID, CognitoUserPoolD

2024-11-08 06:03 UTC, paudelgaurav commented on pkg/framework/env.go
>  	ServerPort  string `mapstructure:"SERVER_PORT"`
ServerPort to Port

2024-11-08 06:03 UTC, paudelgaurav commented on pkg/framework/env.go
> +	DBUsername  string `mapstructure:"DB_USER"`
DBUsername to Username

2025-10-30 07:36 UTC, Denes-cilwal approved these changes
LGTM 🚀

2025-10-30 07:52 UTC, Denes-cilwal commented
I am closing this PR request . The implementation has been merged in postgresql support branch with some code updates
https://github.com/wesionaryTEAM/go_clean_architecture/pull/122

2025-10-30 07:52 UTC, closed without merging