BAC-7 | Refactor Auth Middleware with different roles
WesionaryTEAM/go_clean_architecture pull request #60
Opened 2022-03-16 09:22 UTC by Denes-cilwal

###checklist:
- Admin seeder added 
- Refractor auth middleware based on roles
JIRA :-https://wesionary-team.atlassian.net/jira/software/projects/BAC/boards/61?selectedIssue=BAC-7

2022-03-31 11:32 UTC, Cyantosh0 reviewed
@Denes-cilwal
let's look into some standard ways to handle multiple user roles.

2022-04-12 10:44 UTC, dipeshdulal requested changes

2022-04-12 10:44 UTC, dipeshdulal commented on console/serve.go
> +		migrations.Migrate()
@Denes-cilwal 
I think migrations run automatically after the change in #55. Can you check once?

2022-04-12 10:44 UTC, dipeshdulal commented on console/serve.go
> +		migrations.Migrate()
Or, might be the PR with Unit tests.

2022-04-23 18:01 UTC, Cyantosh0 requested changes
@Denes-cilwal Please go through all the comments.

Also, please update the error handling with the standard one that we are using in our project.

2022-04-23 18:01 UTC, Cyantosh0 commented on api/middlewares/auth_middleware.go
> +	m.handleWithRole(c, &role)
@Denes-cilwal Let's move all the codes from handleWithRole function to this section.
Since, we are calling one function into another function.

2022-04-23 18:01 UTC, Cyantosh0 commented on api/middlewares/auth_middleware.go
> +func (m FirebaseAuthMiddleware) HandleRoles(c *gin.Context, role string) {
@dipeshdulal sir, It seems, roles are now passed from the routes! What do you think about this?

2022-04-23 18:01 UTC, Cyantosh0 commented on api/middlewares/auth_middleware.go
> +	fmt.Println(idToken, "is---")
@Denes-cilwal Why Print idToken here?

2022-04-23 18:01 UTC, Cyantosh0 commented on console/serve.go
> +		migrations.Migrate()
Yes, migration gets run just after the database is initialized. 
@Denes-cilwal remove the migration run here!

2022-04-23 18:01 UTC, Cyantosh0 commented on .env.example
> +ADMIN_EMAIL=test123@gmail.com
let's update the email and password!
I have added the email and password to the Notion's backend environment.

2022-04-23 18:01 UTC, Cyantosh0 commented on api/routes/user_routes.go
> +		s.authMiddleware.HandleRoles(ctx, constants.RoleIsAdmin)
@Denes-cilwal `HandleRoles` does not look a good name. Let's change it to `HandleAuthWithRole`

2022-04-23 18:17 UTC, Denes-cilwal commented on api/middlewares/auth_middleware.go
> +	m.handleWithRole(c, &role)
ok @Cyantosh0  sir

2022-04-23 18:18 UTC, Denes-cilwal commented on api/middlewares/auth_middleware.go
> +func (m FirebaseAuthMiddleware) HandleRoles(c *gin.Context, role string) {
since this is pattern used by many other language as well what do you say @dipeshdulal  sir ?

2022-05-02 06:04 UTC, dipeshdulal commented on api/middlewares/auth_middleware.go
> +func (m FirebaseAuthMiddleware) HandleRoles(c *gin.Context, role string) {
🤔  We can use it.

2022-05-03 10:02 UTC, dipeshdulal commented
I think `HandlerFunc` pattern in middleware is neat.

2022-05-03 12:40 UTC, dipeshdulal commented on console/serve.go
> +		seeds seeds.Seeds,
@Denes-cilwal `migrations` import is un-necessary

2022-05-03 12:40 UTC, dipeshdulal approved these changes

2022-05-04 02:37 UTC, dipeshdulal approved these changes

2022-05-04 02:37 UTC, merged